Code/Chenjing-Lifan/VMManageSystem/Models/VirtualMachineViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VMManageSystem.Models
{
    public class VirtualMachineViewModel
    {
        /// <summary>
        /// 虚拟机列表
        /// </summary>
        public List<VirtualMachineModel> VirtualMachines { get; set; }

        /// <summary>
        /// 员工信息列表
        /// </summary>
        public List<PersonnelModel> Personnels { get; set; }

        /// <summary>
        /// 搜索内容
        /// </summary>
        public string SearchString { get; set; }

        /// <summary>
        /// 电影种类
        /// </summary>
        public string MovieGenre { get; set; }

        /// <summary>
        /// 操作系统
        /// </summary>
        public SelectList OperationSystem { get; set; }

        public string Name { get; set; }
    }
}

Code/Chenjing-Lifan/VMManageSystem/Controllers/VirtualMachinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VMManageSystem.Data;
using VMManageSystem.Models;

namespace VMManageSystem.Controllers
{
    /// <summary>
    /// 虚拟机控制器
    /// </summary>
    public class VirtualMachinesController : Controller
    {
        private readonly VirtualMachineContext _context;

        public VirtualMachinesController(VirtualMachineContext context)
        {
            _context = context;
        }

        #region  后续增加业务

        /// <summary>
        /// 申请页面
        /// </summary>
        /// <returns></returns>
        public IActionResult Apply()
        {
            return View();
        }

        /// <summary>
        /// 申请虚拟机
        /// </summary>
        /// <param name="approvalView"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Apply([Bind("Approval,UsedDays,UsedCount,OperatingSystem")] ApprovalViewModel approvalView)
        {
            //TODO得到申请者Id（Session、Cookie）
            int id = 1;
            //得到申请者对虚拟机最大申请数量
            var personnels = from m in _context.Common_PersonnelInfo
                             where m.PersonnelId == id
                             select m;
            //判断当前用户是否存在
            if (personnels.Any())
            {
                //申请虚拟机
                bool result = await ApplyVM(id, personnels.ToArray()[0].AppMaxCount, approvalView);
                if (result) //如果申请成功
                {
                    //跳转到已申请信息界面
                    return RedirectToAction(nameof(ApprovalDetails));
                }
                else//申请失败，告知用户申请失败原因 
                {
                    return NotFound();
                }
            }
            else //未授权操作
            {
                return NotFound();
            }
        }

        /// <summary>
        /// 申请虚拟机
        /// </summary>
        /// <returns></returns>
        private async Task<bool> ApplyVM(int userId, int maxUsableCount, ApprovalViewModel model)
        {
            bool flag = false;
            //获取可用虚拟机列表
            List<VirtualMachineModel> usableVMs = GetUsableVMs(model.OperatingSystem, MachineStatueEnum.None);
            if (model.UsedCount > maxUsableCount)//超过使用虚拟机最大数
            {
                //向管理员申请，等待管理员审批完成
                _context.MachApplyAndReturn.Add((ApprovalModel)model.Approval.Clone());
                flag = true;
            }
            else//在可申请数量范围内
            {
                //如果申请数量超过空闲数量就使用空闲数量，反之则使用申请数量
                int count = model.UsedCount > usableVMs.Count ? usableVMs.Count : model.UsedCount;
                //申请多个
                for (int i = 0; i < count; i++)
                {
                    //系统自动审批
                    model.Approval.ExamineResult = ApprovalResultEnum.Pass;
                    //系统自动分配虚拟机
                    model.Approval.MachineInfoID = usableVMs[i].MachineId;
                    model.Approval.ApplyUserID = userId;
                    model.Approval.ExamineUserID = 1;//TODO应该为系统Id
                    //修改已分配虚拟机状态
                    _context.MachineInfo.ToList().Find(o =>
                        o.MachineId == model.Approval.MachineInfoID).MachineState = MachineStatueEnum.BeingUsed;
                    //添加审批记录
                    _context.MachApplyAndReturn.Add((ApprovalModel)model.Approval.Clone());
                }
                flag = true;
            }
            await _context.SaveChangesAsync();
            return flag;
        }

        /// <summary>
        /// 获取可用的虚拟机Id集合
        /// </summary>
        /// <param name="os">操作系统</param>
        /// <param name="statue">虚拟机状态</param>
        /// <returns></returns>
        private List<VirtualMachineModel> GetUsableVMs(OperatingSystemEnum os, MachineStatueEnum statue)
        {
            //查询所有符合条件的虚拟机Id
            var vmIds = from m in _context.MachineInfo
                        where m.MachineSystem == os &&
                        m.MachineState == statue
                        select m;
            return vmIds.ToList();
        }

        /// <summary>
        /// 已申请信息
        /// </summary>
        /// <returns></returns>
        public IActionResult ApprovalDetails()
        {
            //查询所有审批单
            var approvals = from m in _context.MachApplyAndReturn
                            orderby m.ExamineResult
                            select m;
            //查询所有员工
            var personnels = from m in _context.Common_PersonnelInfo
                             select m;
            //查询所有虚拟机
            var vms = from m in _context.MachineInfo
                      select m;
            ApprovalViewModel model = new ApprovalViewModel()
            {
                Approvals = approvals.ToList(),
                Personnels = personnels.ToList(),
                VirtualMachines = vms.ToList()
            };
            return View(model);
        }

        /// <summary>
        /// 同意申请
        /// 逻辑：同意后根据Id找到审批单中的申请信息
        /// 再查询所有符合条件虚拟机，将查询得到的第
        /// 一条虚拟机Id赋值给审批单中的虚拟机Id，然
        /// 后将审批人的Id复制审批单中的审批人Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Agree(int? id, int? os)
        {
            //查询所有审批单
            var approvals = from m in _context.MachApplyAndReturn
                            where m.ApplyAndReturnId == id
                            select m;
            //查询所有符合条件的虚拟机Id
            var vmIds = from m in _context.MachineInfo
                        where m.MachineSystem == (OperatingSystemEnum)os &&
                        m.MachineState != MachineStatueEnum.BeingUsed
                        select m.MachineId;
            //查询所有审批单中虚拟机Id
            var appVMIds = from m in _context.MachApplyAndReturn
                           where m.MachineInfoID != 1
                           select m.MachineInfoID;
            //取差集
            var exIds = vmIds.Except(appVMIds);

            if (approvals.Any())
            {
                approvals.ToArray()[0].ExamineResult = ApprovalResultEnum.Pass;
                approvals.ToArray()[0].MachineInfoID = exIds.ToArray()[0];
                _context.MachineInfo.ToList().Find(o => o.MachineId == exIds.ToArray()[0]).MachineState = MachineStatueEnum.BeingUsed;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(ApprovalDetails));
        }

        /// <summary>
        /// 拒绝申请
        /// 逻辑：修改审批单中的状态
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Disagree(int? id)
        {
            var approvals = from m in _context.MachApplyAndReturn
                            where m.ApplyAndReturnId == id
                            select m;
            if (approvals.Any())
            {
                approvals.ToArray()[0].ExamineResult = ApprovalResultEnum.NotPass;
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(ApprovalDetails));
        }

        /// <summary>
        /// 登录
        /// </summary>
        /// <param name="user"></param>
        /// <param name="pwd"></param>
        /// <returns></returns>
        public IActionResult Login(string user, string pwd)
        {
            if (string.IsNullOrWhiteSpace(user) && string.IsNullOrWhiteSpace(pwd))
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                if (user.Equals("JWT") && pwd.Equals("JWT"))
                {
                    ClaimsIdentity identity = new ClaimsIdentity("Forms");
                    identity.AddClaim(new Claim(ClaimTypes.Name, user));
                    identity.AddClaim(new Claim(ClaimTypes.Role, "用户"));//TODO换成具体的权限
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
                    return RedirectToAction(nameof(Index));
                }
                else
                    return RedirectToAction("Login", "Home");
            }
        }

        #endregion

        #region  默认创建的内容

        /// <summary>
        /// 首页
        /// </summary>
        /// <param name="searchString"></param>
        /// <returns></returns>
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Index(string searchString)
        {
            var virtualMachines = from m in _context.MachineInfo
                                  select m;

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                virtualMachines = virtualMachines.Where(options =>
                     options.MachineIP.Contains(searchString) ||
                     options.MachineUser.Contains(searchString));
            }

            OperatingSystemEnum[] operatingSystem = new OperatingSystemEnum[2];
            operatingSystem[0] = OperatingSystemEnum.Windows;
            operatingSystem[1] = OperatingSystemEnum.Linux;
            VirtualMachineViewModel vmModels = new VirtualMachineViewModel()
            {
                OperationSystem = new SelectList(operatingSystem),
                VirtualMachines = await virtualMachines.ToListAsync()
            };


            var personnels = from m in _context.Common_PersonnelInfo
                             select m;

            vmModels.Personnels = personnels.ToList();

Code/Chenjing-Lifan/VMManageSystem/Views/VirtualMachines/Apply.cshtml
@model VMManageSystem.Models.ApprovalViewModel;

@{
    ViewData["Title"] = "Apply";
}

    <p>
        <a asp-action="Index">管理虚拟机</a>
        <a asp-action="Create">添加虚拟机</a>
        <label>申请虚拟机</label>
        <a asp-action="ApprovalDetails">待处理任务</a>
    </p>

<form asp-action="Apply">
    <table id="creating-vm-table">

        <tr id="a">
            <td>
                <b><label class="control-label" style="width:400px;margin-left:300px">操作系统</label></b>
                <select class="form-control" asp-for="OperatingSystem" style="width:400px;margin-left:300px">
                    <option value="0">Windows</option>
                    <option value="1">Linux</option>
                </select>

                <b><label asp-for="UsedDays" class="control-label" style="width:400px;margin-left:300px">使用天数</label></b>
                <select class="form-control" asp-for="UsedDays" style="width:400px;margin-left:300px">
                    <option value="7">7天</option>
                    <option value="15">15天</option>
                    <option value="30">30天</option>
                </select>
                <b><label asp-for="UsedCount" class="control-label" style="width:400px;margin-left:300px">使用数量</label></b>
                <input asp-for="UsedCount" class="form-control" style="width:400px;margin-left:300px" />
                <b><label class="control-label" style="width:400px;margin-left:300px">备注</label></b>
                <textarea asp-for="Approval.Remark" class="form-control" style=" width: 400px;height: 200px; margin-left: 300px"></textarea>
            </td>
        </tr>
    </table>

    <br />
    <input type="submit" value="提交申请" class="btn btn-primary" asp-controller="VirtualMachines" asp-action="Apply" style="width:150px;margin-left:300px" />
    <span class="text-danger"></span>
    <input type="button" value="返回列表" class="btn btn-primary" asp-action="Index" style="width:150px;margin-left:100px" />
    <link href="~/css/Login.css" />
    <div id="org"></div>
</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Code/Chenjing-Lifan/VMManageSystem/Views/VirtualMachines/ApprovalDetails.cshtml
@model VMManageSystem.Models.ApprovalViewModel

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Index">管理虚拟机</a>
    <a asp-action="Create">添加虚拟机</a>
    <a asp-action="Apply">申请虚拟机</a>
    <label>待处理任务</label>
</p>
<form asp-controller="VirtualMachines" asp-action="Index" method="get">
    <p>
        搜索：<input type="text" name="SearchString" />
        <input type="submit" value="开始搜索" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.VirtualMachines[0].MachineIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.VirtualMachines[0].MachineSystem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approval.ApplyUserID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approval.ExamineUserID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approval.ExamineResult)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approval.ApplyTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approval.ResultTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approval.Remark)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Approvals)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.VirtualMachines.Find(o =>
                        o.MachineId == item.MachineInfoID &&
                        item.ExamineResult == VMManageSystem.Data.ApprovalResultEnum.Pass).MachineIP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.VirtualMachines.Find(o => o.MachineId == item.MachineInfoID).MachineSystem)
                </td>
                @*当前用户为管理员角色时展示申请人员姓名，普通用户则不展示*@
                <td>
                    @Html.DisplayFor(modelItem => Model.Personnels.Find(o => o.PersonnelId == item.ApplyUserID).PersonnelName)
                </td>
                @*当前用户为管理员角色时不展示审批人员姓名，普通用户则展示*@
                <td>
                    @Html.DisplayFor(modelItem => Model.Personnels.Find(o => o.PersonnelId == item.ExamineUserID).PersonnelName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamineResult)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplyTime)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.ResultTime)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.Remark)
                </td>
                @{
                    if (item.ExamineResult == VMManageSystem.Data.ApprovalResultEnum.Approving)
                    {
                        <td>
                            <a asp-action="Agree" asp-route-id="@item.ApplyAndReturnId" asp-route-os="0">通过</a> |
                            <a asp-action="Disagree" asp-route-id="@item.ApplyAndReturnId">拒绝</a>
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

Code/Chenjing-Lifan/VMManageSystem/Views/VirtualMachines/Create.cshtml
@model VMManageSystem.Models.VirtualMachineModel

@{
    ViewData["Title"] = "Create";
}

<script type="text/javascript">

    //动态添加控件
    function addInputControl() {
        var tb = document.getElementById("creating-vm-table");

        var docip = document.getElementsByName("machineIP");
        var newTr = tb.insertRow(docip.length + 1);//表示在第二行后添加一行

        var newTdIP = newTr.insertCell();//表示在添加的行上添加第一格
        //newTdIP.innerHTML="邮箱:";
        //var newTd2=newTr.insertCell();//表示在添加的行上添加第二格
        newTdIP.innerHTML = "<input asp-for='MachineIP' class='form-control' name='machineIP' />";

        var newTdSystem = newTr.insertCell();//表示在添加的行上添加第一格
        newTdSystem.innerHTML = "<select class='form-control' asp-for='MachineSystem' name='machineSystem'>" +
            "<option value='0'>Windows</option><option value='1'>Linux</option>" +
            "</select>";

        var newTdDisk = newTr.insertCell();//表示在添加的行上添加第一格
        newTdDisk.innerHTML = "<input asp-for='MachineDiskCount' class='form-control' name='machineDiskCount' />";

        var newTdMemory = newTr.insertCell();//表示在添加的行上添加第一格
        newTdMemory.innerHTML = "<input asp-for='MachineMemory' class='form-control' name='machineMemory' />";

        var newTdState = newTr.insertCell();//表示在添加的行上添加第一格
        newTdState.innerHTML = "<select asp-for='MachineState' class='form-control' name='machineState' >" +
            "<option value='0'>无</option>" +
            "</select>";

        var newTdUser = newTr.insertCell();//表示在添加的行上添加第一格
        newTdUser.innerHTML = "<input asp-for='MachineUser' class='form-control' name='machineUser' />";

        var newTdPwd = newTr.insertCell();//表示在添加的行上添加第一格
        newTdPwd.innerHTML = "<input asp-for='MachinePassword' class='form-control' name='machinePassword' />";
    }

    //批量提交表单
    function submitvmdata() {
        alert('Test');
        //获取多个IP列表
        var iplst = {};
        var doc_ip = document.getElementsByName("machineIP");
        for (var i = 0; i < doc_ip.length; i++) {
            iplst[i] = doc_ip[i].value;
        }

        //获取操作系统列表
        var oslst = {};
        var doc_os = document.getElementsByName("machineSystem");
        for (var i = 0; i < doc_os.length; i++) {
            oslst[i] = doc_os[i].value;
        }

        //获取磁盘容量列表
        var disklst = {};
        var doc_disk = document.getElementsByName("machineDiskCount");
        for (var i = 0; i < doc_disk.length; i++) {
            disklst[i] = doc_disk[i].value;
        }

        //获取内存容量列表
        var memorylst = {};
        var doc_memory = document.getElementsByName("machineMemory");
        for (var i = 0; i < doc_memory.length; i++) {
            memorylst[i] = doc_memory[i].value;
        }

        //获取内存容量列表
        var statelst = {};
        var doc_state = document.getElementsByName("machineState");
        for (var i = 0; i < doc_state.length; i++) {
            statelst[i] = doc_state[i].value;
        }

        //获取机器账号列表
        var userlst = {};
        var doc_user = document.getElementsByName("machineUser");
        for (var i = 0; i < doc_user.length; i++) {
            userlst[i] = doc_user[i].value;
        }

        //获取机器密码列表
        var pwdlst = {};
        var doc_pwd = document.getElementsByName("machinePassword");
        for (var i = 0; i < doc_pwd.length; i++) {
            pwdlst[i] = doc_pwd[i].value;
        }

        var list = [1, 2, 3];
        //获取令牌信息
        var token = $('[name=__RequestVerificationToken]').val();
        $.ajax({
            headers: { "Authorization": token },
            async: false,
            url: "CreateVMs",
            type: "post",
            data: {
                "__RequestVerificationToken": token,
                ipLst: iplst,
                osLst: oslst,
                diskLst: disklst,
                memoryLst: memorylst,
                stateLst: statelst,
                userLst: userlst,
                pwdLst: pwdlst
            },
            success: function (data) {
                window.location.href = data;
            },
        });
    }
</script>

<link href="/css/CreateVMStyle.css" rel="stylesheet" />

<p>
    <a asp-action="Index">管理虚拟机</a>
    <label>添加虚拟机</label>
    <a asp-action="Apply">申请虚拟机</a>
    <a asp-action="ApprovalDetails">待处理任务</a>
</p>

<hr />
<form asp-action="Create">
    <table id="creating-vm-table" ng-controller="c3_4">
        <tr>
            <td style="width:150px"><b><label asp-for="MachineIP" class="control-label"></label></b></td>
            <td style="width:100px"><b><label asp-for="MachineSystem" class="control-label"></label></b></td>
            <td style="width:150px"><b><label asp-for="MachineDiskCount" class="control-label"></label></b></td>
            <td style="width:150px"><b><label asp-for="MachineMemory" class="control-label"></label></b></td>
            <td style="width:100px"><b><label asp-for="MachineState" class="control-label"></label></b></td>
            <td style="width:150px"><b><label asp-for="MachineUser" class="control-label"></label></b></td>
            <td style="width:150px"><b><label asp-for="MachinePassword" class="control-label"></label></b></td>
        </tr>
        <tr>
            <td><input asp-for="MachineIP" class="form-control" name="machineIP" /></td>
            <td>
                <select class="form-control" asp-for="MachineSystem" name="machineSystem">
                    <option value="0">Windows</option>
                    <option value="1">Linux</option>
                </select>
            </td>
            <td><input asp-for="MachineDiskCount" class="form-control" name="machineDiskCount" /></td>
            <td><input asp-for="MachineMemory" class="form-control" name="machineMemory" /></td>
            <td>
                <select asp-for="MachineState" class="form-control" name="machineState">
                    <option value="0">无</option>
                </select>
            </td>
            <td><input asp-for="MachineUser" class="form-control" name="machineUser" /></td>
            <td><input asp-for="MachinePassword" class="form-control" name="machinePassword" /></td>
        </tr>
    </table>
    <input id="ss" type="button" style="margin-left:500px" value="+" class="btn btn-primary" onclick="addInputControl()" />
    <br />
    <input type="button" value="添加虚拟机" class="btn btn-primary" onclick="submitvmdata()" />
    <span class="text-danger"></span>
    <input type="button" value="返回列表" class="btn btn-primary" asp-action="Index" />
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Code/Chenjing-Lifan/VMManageSystem/Views/VirtualMachines/Index.cshtml
@model VMManageSystem.Models.VirtualMachineViewModel
@using System.Security.Claims
@{
    ViewData["Title"] = "Index";
}

<p>
    <label>管理虚拟机</label>
    <a asp-action="Create">添加虚拟机</a>
    <a asp-action="Apply">申请虚拟机</a>
    <a asp-action="ApprovalDetails">待处理任务</a>
</p>
<form asp-controller="VirtualMachines" asp-action="Index" method="get">
    <p>
        搜索：<input type="text" name="SearchString" />
        <input type="submit" value="开始搜索" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.Guid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VirtualMachines[0].PersonneId)
                </th>
            *@
            <th>
                @Html.DisplayNameFor(model => model.VirtualMachines[0].MachineIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VirtualMachines[0].MachineSystem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VirtualMachines[0].MachineState)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.VirtualMachines[0].MachineDiskCount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VirtualMachines[0].MachineMemory)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.VirtualMachines[0].MachineUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VirtualMachines[0].MachinePassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VirtualMachines[0].Approvals.ToArray()[0].Personnel.PersonnelName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.VirtualMachines)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Guid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PersonneId)
                    </td>
                *@
                <td>
                    @Html.DisplayFor(modelItem => item.MachineIP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MachineSystem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MachineState)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MachineUser)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MachinePassword)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.MachineDiskCount)
                    </td>
                *@
                @*<td>
                      @Html.DisplayFor(modelItem => item.Approvals)
                    </td>*@
                <td>
                    @{
                        ApprovalModel approval = item.Approvals.Find(o => o.MachineInfoID == item.MachineId);
                        if (approval != null)
                        {
                            PersonnelModel personnel = Model.Personnels.Find(o => o.PersonnelId == approval.ApplyUserID);
                            if (personnel != null)
                            {
                                @Html.DisplayFor(modelItem => personnel.PersonnelName)
                            }
                        }
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MachineId" asp-access-key="1">编辑</a> |
                    <a asp-action="Details" asp-route-id="@item.MachineId" asp-access-key="1">详情</a> |
                    <a asp-action="Delete" asp-route-id="@item.MachineId" asp-access-key="1">删除</a>
                    <a asp-action="Details" asp-route-id="@item.MachineId" asp-access-key="2">续期</a> |
                    <a asp-action="Delete" asp-route-id="@item.MachineId" asp-access-key="2">回收</a>
                </td>
            </tr>
        }
    </tbody>
</table>