Code/VirtualMachine/Controllers/PersonnelInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VirtualMachine.Data;
using VirtualMachine.Models;
using VirtualMachine.Return;

namespace VirtualMachine.Controllers
{
    public class PersonnelInfoController : FilterController
    {
        /// <summary>
        /// 数据量上下文
        /// </summary>
        private readonly VirtualMachineDB _db;

        /// <summary>
        /// 每页条数
        /// </summary>
        private readonly int pageSize = 10;

        /// <summary>
        /// 角色 
        /// </summary>
        public override int Role { get; set; } = 1;

        public PersonnelInfoController(VirtualMachineDB context)
        {
            _db = context;
        }

        // GET: PersonnelInfo
        public async Task<IActionResult> Index(string name = "", int? pageIndex = 1)
        {
            var list = from c in _db.CommonPersonnelInfo select c;

            if (!string.IsNullOrWhiteSpace(name))
            {
                list = list.Where(o => o.PersonnelName.Contains(name));
            }

            var PagingList = await PaginatedList<CommonPersonnelInfo>.CreateAsync(list, pageIndex ?? 1, pageSize);
            // 查询条件参数
            ViewBag.name = name;
            return View(PagingList);
        }

        // GET: PersonnelInfo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commonPersonnelInfo = await _db.CommonPersonnelInfo
                .FirstOrDefaultAsync(m => m.PersonnelId == id);
            if (commonPersonnelInfo == null)
            {
                return NotFound();
            }

            return View(commonPersonnelInfo);
        }

        // GET: PersonnelInfo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PersonnelInfo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonnelId,PersonnelNo,PersonnelName,DepId,Avatar,PersonnelSex,BirthDate,IdentityCard,IsWork,Nation,MaritalStatus,LiveAddress,Phone,WeChatAccount,Mailbox,Degree,Address,OnboardingTime,DepartureTime,TrialTime,IsStruggle,IsSecrecy,UserName,Password,AppMaxCount")] CommonPersonnelInfo commonPersonnelInfo)
        {
            if (ModelState.IsValid)
            {
                _db.Add(commonPersonnelInfo);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(commonPersonnelInfo);
        }

        // GET: PersonnelInfo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commonPersonnelInfo = await _db.CommonPersonnelInfo.FindAsync(id);
            if (commonPersonnelInfo == null)
            {
                return NotFound();
            }
            return View(commonPersonnelInfo);
        }

        // POST: PersonnelInfo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonnelId,PersonnelNo,PersonnelName,DepId,Avatar,PersonnelSex,BirthDate,IdentityCard,IsWork,Nation,MaritalStatus,LiveAddress,Phone,WeChatAccount,Mailbox,Degree,Address,OnboardingTime,DepartureTime,TrialTime,IsStruggle,IsSecrecy,UserName,Password,AppMaxCount")] CommonPersonnelInfo commonPersonnelInfo)
        {
            if (id != commonPersonnelInfo.PersonnelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(commonPersonnelInfo);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommonPersonnelInfoExists(commonPersonnelInfo.PersonnelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(commonPersonnelInfo);
        }

        // GET: PersonnelInfo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commonPersonnelInfo = await _db.CommonPersonnelInfo
                .FirstOrDefaultAsync(m => m.PersonnelId == id);
            if (commonPersonnelInfo == null)
            {
                return NotFound();
            }

            return View(commonPersonnelInfo);
        }

        // POST: PersonnelInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commonPersonnelInfo = await _db.CommonPersonnelInfo.FindAsync(id);
            _db.CommonPersonnelInfo.Remove(commonPersonnelInfo);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommonPersonnelInfoExists(int id)
        {
            return _db.CommonPersonnelInfo.Any(e => e.PersonnelId == id);
        }
    }
}

Code/VirtualMachine/Controllers/VmwareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using VirtualMachine.Data;
using VirtualMachine.Models;
using VirtualMachine.Return;

namespace VirtualMachine.Controllers
{
    /// <summary>
    /// 申请虚拟机
    /// 控制器
    /// </summary>
    public class VmwareController : FilterController
    {
        /// <summary>
        /// 数据量上下文
        /// </summary>
        private readonly VirtualMachineDB _db;

        /// <summary>
        /// 角色 
        /// </summary>
        public override int Role { get; set; } = 0;

        public VmwareController(VirtualMachineDB context)
        {
            _db = context;
        }

        /// <summary>
        /// GET
        /// Vmware/Index
        /// 查看空闲虚拟机
        /// </summary>
        /// <returns>IActionResult</returns>
        public async Task<IActionResult> Index()
        {
            var list = from m in _db.MachineInfo
                       where m.MachineState == 0    // 空闲状态
                       orderby m.MachineSystem ascending, m.MachineDiskCount ascending, m.MachineMemory ascending
                       group m by new { m.MachineSystem, m.MachineDiskCount, m.MachineMemory } into b
                       select new MachineInfo
                       {
                           MachineSystem = b.Key.MachineSystem,
                           MachineDiskCount = b.Key.MachineDiskCount,
                           MachineMemory = b.Key.MachineMemory,
                           MachineState = b.Count() // 临时当做剩余数量显示
                       };

            return View(await list.ToListAsync());
        }

        // <summary>
        /// GET
        /// Vmware/Apply
        /// 确认申请
        /// </summary>/
        /// <param name="MachineSystem">操作系统 0：Windows 1：Linux</param>
        /// <param name="MachineDiskCount">硬盘大小/G</param>
        /// <param name="MachineMemory">内存大小/G</param>
        /// <param name="FreeNumber">空闲数量</param>
        /// <returns>IActionResult</returns>
        public IActionResult Apply(int machineSystem, double machineDiskCount, double machineMemory, int freeNumber)
        {
            if (machineSystem >= 2 || machineDiskCount == 0 || machineMemory == 0 || freeNumber == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewData["MachineSystem"] = machineSystem;
            ViewData["MachineDiskCount"] = machineDiskCount;
            ViewData["MachineMemory"] = machineMemory;
            ViewData["FreeNumber"] = freeNumber;
            return View();
        }

        /// <summary>
        /// POST
        /// Vmware/SubmitApply
        /// 提交申请
        /// </summary>
        /// <param name="machineSystem">操作系统 0：Windows 1：Linux</param>
        /// <param name="machineDiskCount">硬盘大小/G</param>
        /// <param name="machineMemory">内存大小/G</param>
        /// <param name="applyNumber">申请数量</param>
        /// <param name="remark">备注</param>
        /// <returns>IActionResult</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitApply(int machineSystem, int machineDiskCount, int machineMemory, int applyNumber, string remark)
        {
            // 当前用户信息
            CommonPersonnelInfo userInfo = JsonConvert.DeserializeObject<CommonPersonnelInfo>(HttpContext.Session.GetString("User"));
            // 当前用户ID
            int userId = userInfo.PersonnelId;
            // 最大数量
            int appMaxCount = userInfo.AppMaxCount;

            IEnumerable<MachineInfo> list = from m in _db.MachineInfo
                                            where m.MachineState == 0
                                               && m.MachineSystem == machineSystem
                                               && m.MachineDiskCount == machineDiskCount
                                               && m.MachineMemory == machineMemory
                                            select m;

            // 空闲数量小于申请数量 申请失败
            if (list.Count() < applyNumber)
            {
                ViewData["Title"] = "申请失败";
                ViewData["Message"] = "虚拟机空闲数量不足，请重新申请！";
                return View("Views/Vmware/Error.cshtml");
            }

            // 查询当前用户已申请的数量
            IEnumerable<MachApplyAndReturn> machApplyAndReturnList = from m in _db.MachApplyAndReturn
                                                                     where m.OprationType == 0 && m.ExamineResult == 2 && m.ApplyUserID == userId
                                                                     select m;

            // 未超过数量系统自动审批
            // 超过数量由管理员审批
            // 修改虚拟机状态：申请中
            for (int i = 0; i < applyNumber; i++)
            {
                var model = list.ElementAt(i);
                model.MachineState = ((machApplyAndReturnList.Count() + applyNumber) <= appMaxCount ? 2 : 1);

                _db.MachineInfo.Update(model);

                // 添加到申请记录表
                _db.MachApplyAndReturn.Add(
                    new MachApplyAndReturn()
                    {
                        OprationType = 0,
                        ApplyUserID = userId,
                        ExamineUserID = -1,
                        MachineInfoID = model.MachineId,
                        ExamineResult = ((machApplyAndReturnList.Count() + applyNumber) <= appMaxCount ? 2 : 0),
                        ApplyTime = DateTime.Now,
                        ResultTime = DateTime.Now.AddDays(15), // 默认申请15天
                        Remark = remark
                    });
            }
            await _db.SaveChangesAsync();

            ViewData["Title"] = "申请成功";
            ViewData["Message"] = "申请成功！";
            return View("Views/Vmware/Succeed.cshtml");
        }

        /// <summary>
        /// GET
        /// Vmware/MyVmware
        /// 我的虚拟机
        /// </summary>
        /// <returns></returns>
        public IActionResult MyVmware()
        {
            // 当前用户信息
            CommonPersonnelInfo userInfo = JsonConvert.DeserializeObject<CommonPersonnelInfo>(HttpContext.Session.GetString("User"));

            int userId = userInfo.PersonnelId;

            var list = from m1 in _db.MachineInfo
                       join m2 in _db.MachApplyAndReturn on m1.MachineId equals m2.MachineInfoID
                       where m2.ApplyUserID == userId && m2.OprationType == 0 && m2.ExamineResult == 2
                       select new ReturnMachineInfoApplyData
                       {
                           MachineInfo = m1,
                           MachApplyAndReturn = m2
                       };

            return View(list);
        }

        /// <summary>
        /// 提前归还
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> EarlyReturn(int id)
        {
            // 当前用户信息
            CommonPersonnelInfo userInfo = JsonConvert.DeserializeObject<CommonPersonnelInfo>(HttpContext.Session.GetString("User"));

            int userId = userInfo.PersonnelId;

            if (id == 0)
            {
                ViewData["Title"] = "操作失败";
                ViewData["Message"] = "数据非法，操作终止！";
                return View("Views/Vmware/Error.cshtml");
            }

            var list = from m1 in _db.MachineInfo
                       join m2 in _db.MachApplyAndReturn on m1.MachineId equals m2.MachineInfoID
                       where m2.ApplyAndReturnId == id && m2.ApplyUserID == userId
                       select new ReturnMachineInfoApplyData
                       {
                           MachineInfo = m1,
                           MachApplyAndReturn = m2
                       };

            foreach (var item in list)
            {
                item.MachineInfo.MachineState = 0;
                item.MachApplyAndReturn.OprationType = 1;
                item.MachApplyAndReturn.ResultTime = DateTime.Now;
                _db.MachineInfo.Update(item.MachineInfo);
                _db.MachApplyAndReturn.Update(item.MachApplyAndReturn);
            }

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(MyVmware));
        }


        /// <summary>
        /// 续租
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Relet(int id)
        {
            // 当前用户信息
            CommonPersonnelInfo userInfo = JsonConvert.DeserializeObject<CommonPersonnelInfo>(HttpContext.Session.GetString("User"));

            int userId = userInfo.PersonnelId;

            if (id == 0)
            {
                ViewData["Title"] = "操作失败";
                ViewData["Message"] = "数据非法，操作终止！";
                return View("Views/Vmware/Error.cshtml");
            }

            var list = from m in _db.MachApplyAndReturn
                       where m.ApplyAndReturnId == id && m.OprationType == 0 && m.ApplyUserID == userId
                       select m;

            if (list.Count() == 0)
            {
                ViewData["Title"] = "操作失败";
                ViewData["Message"] = "数据非法，操作终止！";
                return View("Views/Vmware/Error.cshtml");
            }

            foreach (var item in list)
            {

                TimeSpan time = (item.ResultTime - DateTime.Now);
                // 小于三天才能续租
                if (time.Days > 3)
                {
                    ViewData["Title"] = "续租失败";
                    ViewData["Message"] = "虚拟机归还时间必须小于三天！";
                    return View("Views/Vmware/Error.cshtml");
                }

                // 当前时间+15天
                item.ResultTime = DateTime.Now.AddDays(15);

                _db.MachApplyAndReturn.Update(item);
            }

            await _db.SaveChangesAsync();

            ViewData["Title"] = "续租成功";

Code/VirtualMachine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 虚拟机管理</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="#">虚拟机管理系统</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav flex-grow-1">
                        @if (ViewBag.User != null)
                        {
                            @if (ViewBag.User.DepId == 0)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Vmware" asp-action="Index">申请虚拟机</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Vmware" asp-action="MyVmware">我的虚拟机</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Manage" asp-action="Index">管理虚拟机</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Manage" asp-action="Approve">审批虚拟机</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="PersonnelInfo" asp-action="Index">员工管理</a>
                                </li>
                            }
                        }
                    </ul>
                </div>

                <div class="collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewBag.User == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">登录</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <div class="nav-link text-dark">@ViewBag.User.PersonnelName</div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LoginOut">退出</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - 虚拟机管理系统 - <a asp-area="" asp-controller="Vmware" asp-action="Index">XXX</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>