Code/rendelang/VMMachineManage/Controllers/MyMachineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using VMMachineManage.Data;
using VMMachineManage.Models;

namespace VMMachineManage.Controllers
{
    public class MyMachineController : RightsController
    {
        private readonly VMMachineManageContext _context;

        public MyMachineController(VMMachineManageContext context)
        {
            Role = 2;
            _context = context;
        }

        // GET: MyMachine
       
        public async Task<IActionResult> Index(string searchString)
        {
            PersonnelInfoModel userInfo = JsonConvert.DeserializeObject<PersonnelInfoModel>(HttpContext.Session.GetString("User"));
            IQueryable<VMMachineInfoModel> info; 
            info = from m in _context.MachineInfo
                   join m1 in _context.MachApplyAndReturn on m.MachineID equals m1.MachineInfoID
                   join m2 in _context.Common_PersonnelInfo on m1.ApplyUserID equals m2.PersonnelId
                   where(m1.OprationType==0&&m2.PersonnelId== userInfo.PersonnelId)
                   select new VMMachineInfoModel
                   {
                       machineInfo = m,
                       MachApplyAndReturn = m1
                   };
            return View(await info.ToListAsync());
        }

        // GET: MyMachine/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machApplyAndReturnModel = await _context.MachApplyAndReturn
                .FirstOrDefaultAsync(m => m.ApplyAndReturnId == id);
            if (machApplyAndReturnModel == null)
            {
                return NotFound();
            }

            return View(machApplyAndReturnModel);
        }

        // GET: MyMachine/Create
        public IActionResult Create(int id)
        {
            if (id <1)
            {
                return NotFound();
            }

            var machineReturnInfo = from m in _context.MachApplyAndReturn
                                    join m1 in _context.MachineInfo on m.MachineInfoID equals m1.MachineID
                                    where (m.ApplyAndReturnId == id)
                                    select new VMMachineInfoModel
                                    {
                                        machineInfo = m1,
                                        MachApplyAndReturn = m
                                    };
            VMMachineInfoModel vMMachineInfo = machineReturnInfo.FirstOrDefault();

            MachApplyAndReturnModel machApplyAndReturn = vMMachineInfo.MachApplyAndReturn;
            machApplyAndReturn.ResultTime = DateTime.Now;
            machApplyAndReturn.MachineDiskCount = vMMachineInfo.machineInfo.MachineDiskCount;
            machApplyAndReturn.MachineMemory = vMMachineInfo.machineInfo.MachineMemory;
            machApplyAndReturn.MachineSystem = vMMachineInfo.machineInfo.MachineSystem;


            return View(machApplyAndReturn); 
        }

        // POST: MyMachine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, string Remark, int DaysNumber, int ExamineUserName)
        {
            if (ModelState.IsValid)
            {
                PersonnelInfoModel userInfo = JsonConvert.DeserializeObject<PersonnelInfoModel>(HttpContext.Session.GetString("User"));
                var info = from m in _context.MachApplyAndReturn where (m.ApplyAndReturnId == id) select m;
                MachApplyAndReturnModel machApplyAndReturn = info.FirstOrDefault();
                machApplyAndReturn.Remark = Remark;
                machApplyAndReturn.ResultTime = machApplyAndReturn.ResultTime.AddDays(DaysNumber);
                machApplyAndReturn.ExamineUserID = ExamineUserName;
                machApplyAndReturn.OprationType = 0;
                machApplyAndReturn.ExamineResult = 0;
                _context.Update(machApplyAndReturn);

                var machineInfos = from m in _context.MachineInfo where (m.MachineID == machApplyAndReturn.MachineInfoID) select m;
                MachineInfoModel machineInfo = machineInfos.FirstOrDefault();
                machineInfo.MachineState = 1;
                _context.Update(machineInfo);

                var UserInfo = from m in _context.Common_PersonnelInfo.Where(m => m.PersonnelId == userInfo.PersonnelId) select m;
                PersonnelInfoModel personnelInfo = UserInfo.FirstOrDefault();
                personnelInfo.AppMaxCount = personnelInfo.AppMaxCount - 1;
                _context.Update(personnelInfo);

                await _context.SaveChangesAsync();
                
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: MyMachine/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machineReturnInfo = from m in _context.MachApplyAndReturn
                                    join m1 in _context.MachineInfo on m.MachineInfoID equals m1.MachineID
                                    where(m.ApplyAndReturnId==id)
                                    select new VMMachineInfoModel
                                    {
                                        machineInfo = m1,
                                        MachApplyAndReturn = m
                                    };
            VMMachineInfoModel vMMachineInfo = machineReturnInfo.FirstOrDefault();

            MachApplyAndReturnModel machApplyAndReturn = vMMachineInfo.MachApplyAndReturn;
            machApplyAndReturn.ResultTime = DateTime.Now; 
            machApplyAndReturn.MachineDiskCount = vMMachineInfo.machineInfo.MachineDiskCount;
            machApplyAndReturn.MachineMemory = vMMachineInfo.machineInfo.MachineMemory;
            machApplyAndReturn.MachineSystem = vMMachineInfo.machineInfo.MachineSystem;
           

            return View(machApplyAndReturn);
        }

        // POST: MyMachine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,string Remark,DateTime ResultTime,int ExamineUserName)
        {
            if (id <=0)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    PersonnelInfoModel userInfo = JsonConvert.DeserializeObject<PersonnelInfoModel>(HttpContext.Session.GetString("User"));

                    var info = from m in _context.MachApplyAndReturn where (m.ApplyAndReturnId == id) select m;
                    MachApplyAndReturnModel machApplyAndReturn = info.FirstOrDefault();
                    machApplyAndReturn.Remark = Remark;
                    machApplyAndReturn.ResultTime = ResultTime;
                    machApplyAndReturn.ExamineUserID = ExamineUserName;
                    machApplyAndReturn.OprationType = 1;
                    _context.Update(machApplyAndReturn);

                    var machineInfos = from m in _context.MachineInfo where (m.MachineID==machApplyAndReturn.MachineInfoID) select m;
                    MachineInfoModel machineInfo = machineInfos.FirstOrDefault();
                    machineInfo.MachineState = 0;
                    _context.Update(machineInfo);

                    var UserInfo = from m in _context.Common_PersonnelInfo.Where(m => m.PersonnelId == userInfo.PersonnelId) select m;
                    PersonnelInfoModel personnelInfo = UserInfo.FirstOrDefault();
                    personnelInfo.AppMaxCount = personnelInfo.AppMaxCount - 1;
                    _context.Update(personnelInfo);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MachApplyAndReturnModelExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
               
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: MyMachine/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var machApplyAndReturnModel = await _context.MachApplyAndReturn
                .FirstOrDefaultAsync(m => m.ApplyAndReturnId == id);
            if (machApplyAndReturnModel == null)
            {
                return NotFound();
            }

            return View(machApplyAndReturnModel);
        }

        // POST: MyMachine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var machApplyAndReturnModel = await _context.MachApplyAndReturn.FindAsync(id);
            _context.MachApplyAndReturn.Remove(machApplyAndReturnModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MachApplyAndReturnModelExists(int id)

Code/rendelang/VMMachineManage/Views/MyMachine/Create.cshtml
@model VMMachineManage.Models.MachApplyAndReturnModel

@{
    ViewData["Title"] = "Edit";
}

<h1>虚拟机续期</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MachineID" />
            <div class="form-group">
                <label class="control-label">操作系统</label>
                <select disabled="disabled" asp-for="MachineSystem" class="form-control">
                    <option value="0">Windows</option>
                    <option value="1">Linux</option>
                </select>
                <span asp-validation-for="MachineSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">硬盘大小</label>
                <input readonly="readonly" asp-for="MachineDiskCount" class="form-control" />
                <span asp-validation-for="MachineDiskCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">内存大小</label>
                <input readonly="readonly" asp-for="MachineMemory" class="form-control" />
                <span asp-validation-for="MachineMemory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OprationType" class="control-label"></label>
                <select name="OprationType" disabled="disabled" asp-for="OprationType" class="form-control">
                    <option value="1">归还</option>
                </select>
                <span asp-validation-for="OprationType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamineUserName" class="control-label"></label>
                <select name="ExamineUserName" asp-for="ExamineUserName" class="form-control">
                    <option value="1">任德浪</option>
                </select>
                <span asp-validation-for="ExamineUserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplyTime" class="control-label"></label>
                <input readonly="readonly" asp-for="ApplyTime" class="form-control" />
                <span asp-validation-for="ApplyTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">续期天数</label>
                <input name="DaysNumber"  asp-for="DaysNumber" value="3" class="form-control" />
                <span asp-validation-for="DaysNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input readonly="readonly" asp-for="Number" value="1" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p><label class="control-label">续期原因</label></p>
                <textarea name="Remark" asp-for="Remark" class="form-control" value=" 文本域默认值"> </textarea>
                @*<span asp-validation-for="Remark" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="续期" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">返回列表</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Code/rendelang/VMMachineManage/Views/MyMachine/Delete.cshtml
@model VMMachineManage.Models.MachApplyAndReturnModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MachApplyAndReturnModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OprationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OprationType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplyUserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplyUserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamineUserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamineUserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MachineInfoID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MachineInfoID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamineResult)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamineResult)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplyTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplyTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResultTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResultTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Remark)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Remark)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ApplyAndReturnId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Code/rendelang/VMMachineManage/Views/MyMachine/Details.cshtml
@model VMMachineManage.Models.MachApplyAndReturnModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MachApplyAndReturnModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OprationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OprationType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplyUserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplyUserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamineUserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamineUserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MachineInfoID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MachineInfoID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamineResult)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamineResult)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplyTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplyTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResultTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResultTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Remark)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Remark)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ApplyAndReturnId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Code/rendelang/VMMachineManage/Views/MyMachine/Edit.cshtml
@model VMMachineManage.Models.MachApplyAndReturnModel

@{
    ViewData["Title"] = "Edit";
}

<h1>虚拟机归还</h1>
 
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MachineID" />
            <div class="form-group">
                <label class="control-label">操作系统</label>
                <select disabled="disabled" asp-for="MachineSystem" class="form-control">
                    <option value="0">Windows</option>
                    <option value="1">Linux</option>
                </select>
                <span asp-validation-for="MachineSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">硬盘大小</label>
                <input readonly="readonly" asp-for="MachineDiskCount" class="form-control" />
                <span asp-validation-for="MachineDiskCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">内存大小</label>
                <input readonly="readonly" asp-for="MachineMemory" class="form-control" />
                <span asp-validation-for="MachineMemory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OprationType" class="control-label"></label>
                <select name="OprationType" disabled="disabled" asp-for="OprationType" class="form-control">
                    <option value="1">归还</option>
                </select>
                <span asp-validation-for="OprationType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamineUserName" class="control-label"></label>
                <select name="ExamineUserName" asp-for="ExamineUserName" class="form-control">
                    <option value="1">任德浪</option>
                </select>
                <span asp-validation-for="ExamineUserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplyTime" class="control-label"></label>
                <input readonly="readonly" asp-for="ApplyTime" class="form-control" />
                <span asp-validation-for="ApplyTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">归还时间</label>
                <input name="ResultTime" readonly="readonly" asp-for="ResultTime"  class="form-control" />
                <span asp-validation-for="ResultTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input readonly="readonly" asp-for="Number" value="1" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <p><label class="control-label">归还原因</label></p>
                <textarea name="Remark" asp-for="Remark" class="form-control" value=" 文本域默认值"> </textarea>
                @*<span asp-validation-for="Remark" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="归还" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">返回列表</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Code/rendelang/VMMachineManage/Views/MyMachine/Index.cshtml
@model IEnumerable<VMMachineManage.Models.VMMachineInfoModel>

@{
    ViewData["Title"] = "Index";
}

<h1>我的虚拟机</h1>

<form asp-controller="MyMachine" asp-action="Index">
    <p>
        <input type="text" name="searchString" />
        <input class="btn btn-primary" type="submit" value="搜索" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                虚拟机IP
            </th>
            <th>
                操作系统
            </th>
            <th>
                硬盘大小
            </th>
            <th>
                内存大小
            </th>
            <th>
                审批状态
            </th>
            <th>
                登录账号
            </th>
            <th>
                登录密码
            </th>
            <th>
                申请时间
            </th>
            <th>
                归还时间
            </th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.machineInfo.MachineIP)
                </td>
                <td>
                    @if (item.machineInfo.MachineSystem == 0)
                    {
                        <span>Windows</span>
                    }
                    else
                    {
                        <span>Linux</span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.machineInfo.MachineDiskCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.machineInfo.MachineMemory)
                </td>

                @if (item.MachApplyAndReturn.ExamineResult == 0)
                {
                    <td>待审批</td>

                    <td></td>
                    <td></td>
                }
                else if (item.MachApplyAndReturn.ExamineResult == 1)
                {
                    <td>拒绝</td>
                    <td></td>
                    <td></td>
                }
                else
                {
                    <td>同意</td>
                    <td>@item.machineInfo.MachineUser</td>
                    <td>@item.machineInfo.MachinePassword</td>
                }

                <td>
                    @Html.DisplayFor(modelItem => item.MachApplyAndReturn.ApplyTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MachApplyAndReturn.ResultTime)
                </td>
                <td>
                    @if (item.MachApplyAndReturn.ExamineResult == 2)
                    {
                        <a asp-action="Edit" asp-route-id="@item.MachApplyAndReturn.ApplyAndReturnId" class="btn btn-primary btn-sm">归还</a>

                      
                            <a class="btn btn-primary btn-sm" asp-action="Create" asp-route-id="@item.MachApplyAndReturn.ApplyAndReturnId">续租</a>
                        
                    }
                </td>
            </tr>
        }
    </tbody>
</table>